print('welcome to my room')
name= input('now we will fill the base together')
print('Okay,let is go', name)
print('pleasу enter your detailes:FullName,Phone,Mail,Date of Birth,Adress,Grown,Weight,Experience')
FullName = input('pleasу write your FullName:' )
Phone = input('pleasу write your Phone:' )
Mail = input('pleasу write your Mail:' )
DateofBirth = input('pleasу write your Date of Birth:' )
Adress = input('pleasу write your Adress:' )
Grown = input('pleasу write your Grown:' )
Weight = input('pleasу write your Weight:' )
Experience = input('pleasу write your Experience:')
print('My FullName :',FullName,'\nMy Phone :',Phone,'\nMy Mail :',Mail,'\nMy DateofBirth :',DateofBirth,'\nMy Adress',Adress,'\nMy Grown',Grown,'\nMy Weight',Weight,'\nMy Experience',Experience )
print('\tVery well,we will save your data')